# Generated by Django 2.2.6 on 2019-10-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='descricao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
