# Generated by Django 2.2.6 on 2019-10-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recurso_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
